### ISSUE TITLE
Feature: improve snap controls to be able to snap on geometries, not only fix markers

### ISSUE THREAD

**Issue by onderaltintas** [geops/openlayers-editor#135]
Hi there,

Few months or so ago I saw this repository. Nice work, I liked it very much. Especially union/intersection/buffer etc. things are cool!

On the other hand, some controls are a bit confusing. Either I didn't understand how to use em or there could be some malfunction. For example I see a bit strange behavior while using snap controls. Here are the steps to reproduce the problem:

1- Put a point on a map with using "draw point" tool.
2- Snap is opened. 0 px 10 px it won't matter.
3- There are x signs at 4 side of point. The controller snaps these x signs.
4- How to exactly start a line from the exact location of point? I could find there is no way to snap on the point but 4 x marks.

This one works with lines, have strange issues with polygons (never puts a point at snap location). 

I didn't get the idea behind the requirement of adding x signs around the vertices. OpenLayer's snap control works well in my opinion except not being able to snap the currently drawing geometry (or can be done that I don't know the way yet). I believe you are planning to implement snap controls like AutoCAD's. They do good job as well. 

By the way, also I am working on a hobbyish thing atm if ye wanna check (can see ol snapping already):
https://onderaltintas.github.io/arz/

Have fun,

**Comment by lb1c** [comment]
Hi there,
just grasping on the stale issues.
To clarify, is this a documentation issue or are you suggesting a different behaviour?

**Comment by onderaltintas** [comment]
Hello there, 

Sorry I just saw it. As an update, I meant snap control's current behaviour is not expected. 

I recorded video on your website: http://openlayers-editor.geops.de/

Snap -by its name- should snap to the edge or the closest point on geometries. It behaves that way in AutoCad, NetCAD, Microstation, Openlayers and such other things. I did not understand why snap control puts 4 x marks around edges and you can only snap on em but not on geometry. It is not expected behaviour while you are trying to snap to the edge of the line or a point.

Here are the videos to make sure we are on same page, first one is geops oled behaviour and second one is the microstation behaviour, but you can check the other cad applications as well:
https://www.youtube.com/watch?v=8rPEM0ZmmkM&feature=youtu.be

https://www.youtube.com/watch?v=Hcyh8sDfGHc

Regards,

**Comment by lb1c** [comment]
Thanks for the information.
As far as i know, the snapping by points with a fixed distance was a necessary requirement for an internal project.
By activating `Show snap lines` the snaping behaviour show not the point markers but helper lines, that are drawn for the points of the nearby geometries in order to be able to adjust items accoring to it's surrounding.

But i agree, that a "snap onto an existing edge of a geometry" is currently not possible.

So i will mark this issue a feature request but i cannot promise implementation.

**Comment by jlgranda** [comment]
Try const cad = new CADControl({
              source: layer.getSource(),
              title: "Regla - Permite establecer los puntos de referencia de los elementos.",
              snapTolerance: 14,
              snapPointDist: 1,
              useMapUnits: false,
            });
