### ISSUE TITLE
Move to new OL6 select interaction

### ISSUE THREAD

**Issue by friedjoff** [geops/openlayers-editor#141]
In #140 we upgraded to OpenLayers 6 release. This release has breaking changes in the select interaction, so we copied the old implementation to our repository.

We should try to move to the new OL6 select interaction to minimize code duplication and maximize compatibility with OL.

**Comment by oterral** [comment]
At some point, we should write our own behavior without the official Select Interaction, it shouldn't be so hard. 
OL has removed the Select interaction before re-adding it for the release. See https://github.com/openlayers/openlayers/pull/9961
