### ISSUE TITLE
Unable to process features when select second feature todo Union.

### ISSUE THREAD

**Issue by aim8526** [geops/openlayers-editor#144]
when i try to merge two feature got **Error:- Unable to process features**

Also,
I created Vector layer using vector source url (geoserver).
So, how can i update changes in postgis db ?
how can i build undo, redo controls and split feature

**Comment by oterral** [comment]
@aim8526 do you use the last version ?   a codepen/jsfiddle/codesandbox example would be nice.

> how can i build undo, redo controls and split feature
To build undo/redo functionnality, just clone the content of your vector source on each change  then reapply it .

> So, how can i update changes in postgis db ?
have a look to WFS-T OGC specification.  Geoserver implements  it

**Comment by aim8526** [comment]
I have not found any codepen or sandbox for openlayer-editor.

Can you share the code snippets or code documentation for the same.
