### ISSUE TITLE
Snap 

### ISSUE THREAD

**Issue by jlgranda** [geops/openlayers-editor#217]
The snap does not allow to join the features without a space between them
![Peek 04-12-2020 12-41](https://user-images.githubusercontent.com/1143320/101197160-bdc37c00-362f-11eb-89ba-235d328cec25.gif)

**Comment by oterral** [comment]
Good catch. Fixed with #220 . Can you confirm  it works for you ?

**Comment by friedjoff** [comment]
Has been released with v2.0.1.

**Comment by jlgranda** [comment]
It does not allow to coincide with the vertices. This generates gaps and possible overlaps
