### ISSUE TITLE
Running this project from scratch gives error : "  'ole' is not defined "

### ISSUE THREAD

**Issue by GreenUtil** [geops/openlayers-editor#218]
![image](https://user-images.githubusercontent.com/2122311/105029867-356c2f80-5a53-11eb-8b67-3ffa8c395f34.png)

Greetings from the Netherlands

**Comment by oterral** [comment]
omg. Thanks for pointing this out. I've fixed the README https://github.com/geops/openlayers-editor/commit/2a451c929b86d5755f33977fb6615e7584ee1e67 .

Just run 'npm run build' before 'npm start' then it should work.
