### ISSUE TITLE
Help wanted :  the modify tool, it moves the geometry, how to modify vertices ?

### ISSUE THREAD

**Issue by GreenUtil** [geops/openlayers-editor#219]
When selecting the modify tool, it seems all you can do is move the geometry.
What should be done to modify vertices ?

![image](https://user-images.githubusercontent.com/2122311/105045067-c2b97f00-5a67-11eb-9d7d-03a9b44bc9ac.png)

Greetings from the Netherlands

**Comment by oterral** [comment]
Single click  -> select for move
Double click -> select for modify
