### ISSUE TITLE
OLE can't depend on OL loaded with webpack

### ISSUE THREAD

**Issue by MartinRixhamEE** [geops/openlayers-editor#99]
I'm trying to package my app that uses open layers using webpack.
I loaded ole from node_modules in my main.js file

    import ole from 'ole';

and I provided the ol library directly in webpack.config.js

    new webpack.ProvidePlugin({
         "ol": "ol"
     })

Webpack ran without any errors but running the bundle in chrome browser I got the following exception:

Uncaught TypeError: Cannot read property 'Control' of undefined
    at Object.<anonymous> (main.js:24772)
    at t (main.js:24510)
    at Object.<anonymous> (main.js:24698)
    at t (main.js:24510)
    at Object.<anonymous> (main.js:24685)
    at t (main.js:24510)
    at Object.<anonymous> (main.js:24682)
    at t (main.js:24510)
    at main.js:24521
    at main.js:24522

the line that broke looks like this 

    }(ol.control.Control);t.a = c;

sorry I couldn't get it un-minified

**Comment by oterral** [comment]
@MartinRixhamEE yes ole doesn't import ol as es6 modules. for some old projects backward compatibility reasons ol and jsts must be loaded in the index.html file. 

We will wait for ol to support:
```
import {ol} from 'openlayers` 
``` 
In the mean time in  [react-spatial](https://github.com/geops/react-spatial/) we provide an (utility class)[https://github.com/geops/react-spatial/blob/master/src/utils/GlobalsForOle.js] to import all global variables needed by ole.  If you import this file before importing ole, it should work.

**Comment by MartinRixhamEE** [comment]
Thank you for the workaround and your quick reply
